ERV/ERV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # aai
    path('saml2/', include('djangosaml2.urls')),

    path("main/", include(("main.urls", "main"), namespace="main")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ERV/main/urls.py
from django.urls import path
from . import views 

app_name = 'main'

urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('upload_form', views.upload_form, name='upload_form'),
    path('upload_csv', views.upload_csv, name='upload_csv'),
    path('add_erv', views.add_erv, name='add_erv'),
    path('add_worker', views.add_worker, name='add_worker'),
    path("erv_table/", views.ErvTable.as_view(), name="erv_table"),
    path('swap_erv_table/', views.SwapErvTable.as_view(), name='swap_erv_table'),
    path('erv_table/jobs', views.Jobs.as_view(), name='jobs'),
    path('edit_erv/<int:pk>/', views.edit_erv, name='edit_erv'),
    path('remove_erv/<int:pk>/', views.remove_erv, name='remove_erv'),
    path('bar_graph/<int:pk>/<str:year>/<str:month>/', views.bar_graph, name='bar_graph'),
    path('pie/<int:pk>/<str:year>/<str:month>/', views.pie, name='pie'),
    path('total_pie/<str:year>/<str:month>/', views.total_pie, name='total_pie'),
    path('total_pie_partial/<str:year>/<str:month>/', views.total_pie_partial, name='total_pie_partial')
]

ERV/main/models.py
from django.db import models
from datetime import date, datetime 

CATEGORY_CHOICES = {
    ('Administracija', 'Administracija'),
    ('Nastavnici', 'Nastavnici')
}

FLAG_CHOICES = {
    ('Redovni rad', 'Redovni rad'),
    ('Putni nalog', 'Putni nalog'),
    ('Bolovanje', 'Bolovanje'),
    ('Slobodan dan', 'Slobodan dan'),
    ('Godišnji odmor', 'Godišnji odmor'),
    ('Rad od kuće', 'Rad od kuće')
}


class Job(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=15, choices=CATEGORY_CHOICES)
   
    def __str__(self):
        return self.name

class Worker(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    active = models.BooleanField(default=True)
    job = models.ForeignKey(Job, on_delete=models.PROTECT) 

    def __str__(self):
        return self.name + ' ' + self.surname
    
    class Meta:
        unique_together = ('name', 'surname')
        ordering = ['surname']


class ERV(models.Model):
    worker = models.ForeignKey(Worker, on_delete=models.PROTECT, verbose_name='Radnik')
    current_date = models.DateField('Razdoblje', default=date.today)
    enter_time = models.TimeField('Vrijeme ulaska', null=True, blank=True)
    exit_time = models.TimeField('Vrijeme izlaska', null=True, blank=True)
    delta_time = models.TimeField('Vrijeme rada', null=True, blank=True)
    flag = models.CharField('Vrsta rada', max_length=14, choices=FLAG_CHOICES, blank=True, null=True)
    processed = models.BooleanField('Potvrdi', default=False)

    class Meta:
        unique_together = ('worker', 'current_date')
        ordering = ['-current_date']

    def save(self, *args, **kwargs):
        FORMAT_TIME = '%H:%M:%S'
        if self.enter_time != None and self.exit_time != None:
            exit = datetime.combine(self.current_date, self.exit_time)
            enter = datetime.combine(self.current_date, self.enter_time)
            delta = str(exit - enter)
            self.delta_time = datetime.strptime(delta, FORMAT_TIME)
        super(ERV, self).save(*args, **kwargs)

    def __str__(self):
        return self.worker.name + ' ' + self.worker.surname + ' ' +  str(self.current_date) + ' ' + str(self.enter_time) + ' - ' + str(self.exit_time)

# load fixture sa ./manage.py loaddata data.json
# DEPRECATED
class Marker(models.Model):
    value = models.IntegerField(default=0)

ERV/main/forms.py
from datetime import datetime 
from django import forms
from .models import ERV, Worker

class AddErvForm(forms.ModelForm):
    class Meta:
        model=ERV
        fields = ['worker', 'current_date', 'enter_time', 'exit_time', 'flag', 'processed']
        widgets = {
            'current_date': forms.widgets.DateInput(attrs={'type': 'date'}),
            'enter_time': forms.widgets.TimeInput(attrs={'type': 'time'}),
            'exit_time': forms.widgets.TimeInput(attrs={'type': 'time'})
        }

    def clean(self):
        super(AddErvForm, self).clean()

        worker  = self.cleaned_data.get('worker')
        flag  = self.cleaned_data.get('flag')
        enter_time = self.cleaned_data.get('enter_time')
        exit_time = self.cleaned_data.get('exit_time')
        current_date = self.cleaned_data.get('current_date')
        processed = self.cleaned_data.get('processed')

        if flag == None:
            self._errors['flag'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])

        if processed == False:
            self._errors['processed'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])

        if exit_time == None:
            self._errors['exit_time'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])
        if enter_time == None:
            self._errors['enter_time'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])

        if exit_time != None and enter_time != None:
            exit = datetime.combine(current_date, exit_time)
            enter = datetime.combine(current_date, enter_time)
            if exit.time() <= enter.time():
                self._errors['exit_time'] = self.error_class([
                    'Vrijeme izlaska ne može biti prije vremena ulaska'
                ])

        if ERV.objects.filter(current_date = current_date, worker__id = worker.id).exists():
            self._errors['current_date'] = self.error_class([
                'Ovaj ERV već postoji'
            ])
            self._errors['worker'] = self.error_class([
                'Ovaj ERV već postoji'
            ])

        return self.cleaned_data

class EditErvForm(forms.ModelForm):
    class Meta:
        model=ERV
        fields = ['worker', 'current_date', 'enter_time', 'exit_time', 'flag', 'processed']
        widgets = {
            'current_date': forms.widgets.DateInput(attrs={'type': 'date'}),
            'enter_time': forms.widgets.TimeInput(attrs={'type': 'time'}),
            'exit_time': forms.widgets.TimeInput(attrs={'type': 'time'})
        }

    def clean(self):
        super(EditErvForm, self).clean()

        worker  = self.cleaned_data.get('worker')
        flag  = self.cleaned_data.get('flag')
        enter_time = self.cleaned_data.get('enter_time')
        exit_time = self.cleaned_data.get('exit_time')
        current_date = self.cleaned_data.get('current_date')
        processed = self.cleaned_data.get('processed')

        if flag == None:
            self._errors['flag'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])

        if processed == False:
            self._errors['processed'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])

        if exit_time == None:
            self._errors['exit_time'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])
        if enter_time == None:
            self._errors['enter_time'] = self.error_class([
                'Morate ispuniti ovo polje'
            ])

        if exit_time != None and enter_time != None:
            exit = datetime.combine(current_date, exit_time)
            enter = datetime.combine(current_date, enter_time)
            if exit.time() <= enter.time():
                self._errors['exit_time'] = self.error_class([
                    'Vrijeme izlaska ne može biti prije vremena ulaska'
                ])

        return self.cleaned_data

class WorkerForm(forms.ModelForm):
    class Meta:
        model=Worker
        fields = ['name', 'surname', 'active', 'job']

    def clean(self):
        super(WorkerForm, self).clean()

        name  = self.cleaned_data.get('name')
        surname = self.cleaned_data.get('surname')

        if Worker.objects.filter(name__iexact = name, surname__iexact = surname).exists():
            self._errors['name'] = self.error_class([
                'Ovaj radnik već postoji'
            ])
            self._errors['surname'] = self.error_class([
                'Ovaj radnik već postoji'
            ])

        return self.cleaned_data

ERV/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from main.models import *
from django.http import HttpResponse
from django.core.files.storage import default_storage
from ERV.settings import BASE_DIR
from utils.loadingCSV_from_upload import uploading_csv, validate_file_extension, validate_file_content_type
from utils.bar_graph_data import graph_data_dict, specific_pie_chart, total_pie_chart
from django.contrib import messages
from main.tables import ProductHTMxMultiColumnTable
from main.filters import ErvFilter
from django.core.paginator import Paginator, EmptyPage
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView
from .forms import  AddErvForm, WorkerForm, EditErvForm
from django.shortcuts import get_object_or_404, get_list_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django_tables2.export.views import ExportMixin
import json 

# Create your views here.
class WorkerList(ListView):
    model = ERV

@login_required
def homepage(request):
    return render(request, 'base_generic.html')

@login_required
def upload_form(request):
    return render(request, 'partials/upload_form.html')

@login_required
def upload_csv(request):
    if request.method == 'POST':
        csv = request.FILES.get('csv')
        if len(request.FILES) != 0 and validate_file_extension(csv) and validate_file_content_type(csv):
            csv_name = default_storage.save('csv_file', csv)
            csv_url = str(BASE_DIR) + default_storage.url(csv_name)
            
            try:
                uploading_csv(csv_url)
                default_storage.delete(csv_url)
                messages.success(request, 'CSV datoteka uspješno učitana')
                return HttpResponse(status=200, headers={'HX-Trigger': 'Changed'})
            except:
                default_storage.delete(csv_url)
                messages.error(request, 'Problem s CSV datotekom')
                return HttpResponse(status=400)
            
        else:
            messages.error(request, 'Potrebno je odabrati CSV datoteku')
            return HttpResponse(status=400)

@login_required    
def add_erv(request):
    if request.method == "POST":
        form = AddErvForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'ERV uspješno dodan')
            return HttpResponse(status=200, headers={'HX-Trigger': 'Changed'})
    else:
        form = AddErvForm()
    return render(request, 'partials/erv_form.html', {
        'form': form,
    })

@login_required
def add_worker(request):
    if request.method == "POST":
        form = WorkerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Radnik uspješno dodan')
            #HttpResponse(status=200)
            return redirect('main:add_erv')
    else:
        form = WorkerForm()
    return render(request, 'partials/worker_form.html', {
        'form': form,
    })


class CustomPaginator(Paginator):
    def validate_number(self, number):
        try:
            return super().validate_number(number)
        except EmptyPage:
            if int(number) > 1:
                # return the last page
                return self.num_pages
            elif int(number) < 1:
                # return the first page
                return 1
            else:
                raise

""" class ErvTable(LoginRequiredMixin, SingleTableMixin, FilterView, ExportMixin):
    table_class = ProductHTMxMultiColumnTable
    #queryset = ERV.objects.all()
    model = ERV
    filterset_class = ErvFilter
    paginate_by = 10
    paginator_class = CustomPaginator
    export_formats = ['csv', 'xls']

    def get_context_data(self, *args, **kwargs):
        context = super(ErvTable, self).get_context_data(*args,**kwargs)
        context['workers'] = Worker.objects.all()
        return context

    def get_template_names(self):
        if self.request.htmx:
            template_name = "tables/table_partial.html"
        else:
            template_name = "tables/table_filter.html"
        return template_name
 """


class ErvTable(ExportMixin, SingleTableMixin, FilterView, LoginRequiredMixin):
    table_class = ProductHTMxMultiColumnTable
    queryset = ERV.objects.all()
    filterset_class = ErvFilter
    paginate_by = 10
    paginator_class = CustomPaginator

    def get_context_data(self, *args, **kwargs):
        context = super(ErvTable, self).get_context_data(*args,**kwargs)
        context['workers'] = Worker.objects.all()
        return context

    def get_template_names(self):
        if self.request.htmx:
            template_name = "tables/table_partial.html"
        else:
            template_name = "tables/table_filter.html"
        return template_name

class SwapErvTable(ExportMixin, SingleTableMixin, FilterView, LoginRequiredMixin):
    table_class = ProductHTMxMultiColumnTable
    queryset = ERV.objects.all()
    filterset_class = ErvFilter
    paginate_by = 10
    paginator_class = CustomPaginator
    template_name = "tables/swap.html"

    def get_context_data(self,*args, **kwargs):
        context = super(SwapErvTable, self).get_context_data(*args,**kwargs)
        context['workers'] = Worker.objects.all()
        return context


class Jobs(LoginRequiredMixin, FilterView):
    filterset_class = ErvFilter
    template_name = "partials/jobs_form.html"

@login_required
def edit_erv(request, pk):
    erv = get_object_or_404(ERV, pk=pk)
    if request.method == "POST":
        form = EditErvForm(request.POST, instance=erv)
        if form.is_valid():
            form.save()
            messages.success(request, 'ERV ažuriran')
            return HttpResponse(status=200, headers={'HX-Trigger': 'Changed'})
    else:
        form = EditErvForm(instance=erv)
    return render(request, 'partials/erv_form.html', {
        'form': form,
        'erv': erv,
    })

@login_required
@ require_POST
def remove_erv(request, pk):
    erv = get_object_or_404(ERV, pk=pk)
    erv.delete()
    messages.warning(request, 'ERV uklonjen')
    return HttpResponse(status=200, headers={'HX-Trigger': 'Changed'})

@login_required
def bar_graph(request, pk, year, month='Ukupno'):
    selectedErv = get_object_or_404(ERV, pk=pk)
    selectedWorker = selectedErv.worker
    workerErvs = get_list_or_404(ERV, worker=selectedWorker)
    graphs=graph_data_dict(workerErvs, year)
    context = {
        'bar_chart':json.dumps(graphs['bar_chart']),
        'pie_chart':json.dumps(graphs['pie_chart']),
        'months':['Ukupno']+graphs['bar_chart']['labels'],
        'years':graphs['years'],
        'pk':pk,
        'current_year':year,
        'current_month':month,
        'worker': workerErvs[0].worker.name + ' ' + workerErvs[0].worker.surname
        }
    #print(context)
    return render(request, 'graphs/graph.html', context)

@login_required
def pie(request, pk, year, month='Ukupno'):
    selectedErv = get_object_or_404(ERV, pk=pk)
    selectedWorker = selectedErv.worker
    workerErvs = get_list_or_404(ERV, worker=selectedWorker)
    pie_chart=specific_pie_chart(workerErvs, year, month)
    context = {
        'pie_chart':json.dumps(pie_chart),
        'months':['Ukupno']+pie_chart['months'],
        'pk':pk,
        'current_year':year,
        'current_month':month,
        }
    #print('hi')
    return render(request, 'graphs/specific_pie_chart.html', context)

@login_required
def total_pie(request, year, month='Ukupno'):
    allErvs = get_list_or_404(ERV)
    print(allErvs)
    pie_chart=total_pie_chart(allErvs, year, month)
    context = {
        'pie_chart':json.dumps(pie_chart),
        'months':['Ukupno']+pie_chart['months'],
        'years': pie_chart['years'],
        'current_year':year,
        'current_month':month,
        }
    #print(context)
    return render(request, 'graphs/total_pie_chart.html', context)

@login_required
def total_pie_partial(request, year, month='Ukupno'):
    allErvs = get_list_or_404(ERV)
    print(allErvs)
    pie_chart=total_pie_chart(allErvs, year, month)
    context = {
        'pie_chart':json.dumps(pie_chart),
        'months':['Ukupno']+pie_chart['months'],
        'years': pie_chart['years'],
        'current_year':year,
        'current_month':month,
        }
    #print(context)
    return render(request, 'graphs/total_pie_partial.html', context)

ERV/main/templates/partials/category_selection.html
<select name="category" class="vrsta-posla" hx-get="{% url 'main:category_list' %}" hx-target="#selected_category" hx-trigger="onload">
    <option class="option_title" value="" selected>Vrsta posla</option>
    <option value="administracija" >Administracija</option>
    <option value="nastavnici" >Nastavnici</option>
    <!-- {% for job in jobs %}
        <option class="categories" > {{job}} </option>
    {% endfor %} -->
</select>

ERV/main/templates/partials/edit_button.html
{% load static %}
<button
  hx-get="{% url 'main:edit_erv' record.id %}"
  hx-target="#dialog"
  hx-trigger="click"
  hx-swap="innerHTML"
  class="border-0 bg-transparent position-absolute"
>
  <i class="bi bi-pencil-square"></i>
  <!--<img
    src="{% static 'img/edit-icon.png' %}"
    alt="vector"
    class="vector"
    style="width: 25% !important; height: 25% !important"
  />-->
</button>

ERV/main/templates/partials/erv_form.html
{% load widget_tweaks %} {% with WIDGET_ERROR_CLASS='is-invalid' %}
<form
  hx-post="{{ request.path }}"
  hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
  class="modal-content"
>
  <div class="modal-header">
    <h3 class="modal-title">Dodja Evidenciju radnog vremena</h3>
  </div>

  <div class="modal-body">
    <div class="mb-3">
      <label for="{{ form.worker.id_for_label }}" class="form-label"
        >Radnik</label
      >
      <div class="input-group">
        {% render_field form.worker class="form-control" %}
        <button
          type="button"
          class="btn btn-success"
          hx-get="{% url 'main:add_worker' %}"
        >
          +
        </button>
      </div>
      <div class="invalid-feedback input-medium">
        {{ form.worker.errors|first }}
      </div>
    </div>

    <div class="mb-3">
      <label for="{{ form.current_date.id_for_label }}" class="form-label"
        >Datum</label
      >
      {% render_field form.current_date class="form-control" %}
      <div class="invalid-feedback input-small">
        {{ form.current_date.errors|first }}
      </div>
    </div>

    <div class="mb-3">
      <label for="{{ form.enter_time.id_for_label }}" class="form-label"
        >Vrijeme ulaska</label
      >
      {% render_field form.enter_time class="form-control" %}
      <div class="invalid-feedback">{{ form.enter_time.errors|first }}</div>
    </div>

    <div class="mb-3">
      <label for="{{ form.exit_time.id_for_label }}" class="form-label"
        >Vrijeme izlaska</label
      >
      {% render_field form.exit_time class="form-control" %}
      <div class="invalid-feedback">{{ form.exit_time.errors|first }}</div>
    </div>

    <div class="mb-3">
      <label for="{{ form.flag.id_for_label }}" class="form-label"
        >Vrsta rada</label
      >
      {% render_field form.flag class="form-control" %}
      <div class="invalid-feedback">{{ form.flag.errors|first }}</div>
    </div>

    <div class="mb-3">
      <label for="{{ form.processed.id_for_label }}" class="form-label"
        >Potvrdi</label
      >
      {% render_field form.processed class="form-check-input" type="checkbox"%}
      <div class="invalid-feedback">{{ form.processed.errors|first }}</div>
    </div>
  </div>

  <div class="modal-footer">
    {% if erv %}
    <button
      type="button"
      class="btn btn-danger"
      hx-post="{% url 'main:remove_erv' erv.pk %}"
      hx-confirm="Odabrani ERV biti će uklonjen. Želite li nastaviti?"
    >
      Ukloni
    </button>
    <span class="flex-grow-1"></span>
    {% endif %}
    <button
      style="
        border-radius: 6px;
        background-color: #6cb5b5;
        border: none;
        padding: 5px 10px;
        text-align: center;
        margin: 4px 2px;
        opacity: 0.5;
        transition: 0.3s;
        display: inline-block;
        cursor: pointer;
        color: black;
        font-weight: bold;
      "
      type="button"
      class="btn"
      data-bs-dismiss="modal"
    >
      Odustani
    </button>
    <button
      style="
        background-color: #8cd8a6;
        border-radius: 6px;
        border: none;
        padding: 5px 10px;
        text-align: center;
        margin: 4px 2px;
        opacity: 1;
        transition: 0.3s;
        display: inline-block;
        cursor: pointer;
        color: black;
        font-weight: bold;
      "
      type="submit"
      class="btn"
    >
      Spremi
    </button>
  </div>
</form>
{% endwith %}

ERV/main/templates/partials/filter.html
{% extends "base_generic.html" %}
<!-- {% load static %}
<link
rel="stylesheet"
type="text/css"
href="{% static 'css/style.css' %}"
/> -->
{% block form %}
<form hx-post="/search-worker" action="{% url 'main:search-worker' %}" autocomplete='off' class="filters">
    {% csrf_token %}
      <div class="overlap-group1-1">
        <div class="decoration-2 decoration-4"></div>
        <div class="overlap-group-3">
        <input class="pretrazivanje-radnika" type="text"  name="search_worker" placeholder="Pretraživanje radnika"></input>
        <img src="{% static 'img/search-vector.svg' %}" alt="Vector" class="vector-2" />
      </div>
      </div>
      <div class="overlap-group1-0">
        <div class="decoration decoration-4"></div>
        <div class="overlap-group-1-0" id="containerCal">
          <input id="myCal"  class="cal-content vrsta-posla" type="text" name="daterange" onclick="calendar()"/>
          <input id="showCal" type="checkbox" checked onclick="check()">
          <p id="textShow">Prikaži kalendar</p>
        </div>
      </div>
      <div class="overlap-group">
        <div class="decoration-5 decoration-4"></div>
        <div class="overlap-group-1" id="selected_category">
          {% include 'partials/category_selection.html' %}
        </div>
      </div>

      <div class="overlap-group2-1">
        <div class="decoration-3 decoration-4"></div>
        <div class="overlap-group-4">
          <select name="month" class="mjesec">
            <option class="option_title"  value="" selected>Mjesec</option>
            <option value="1">Siječanj</option>
            <option value="2">Veljača</option>
            <option value="3">Ožujak</option>
            <option value="4">Travanj</option>
            <option value="5">Svibanj</option>
            <option value="6">Lipanj</option>
            <option value="7">Srpanj</option>
            <option value="8">Kolovoz</option>
            <option value="9">Rujan</option>
            <option value="10">Listopad</option>
            <option value="11">Studeni</option>
            <option value="12">Prosinac</option>
          </select>
        </div>
      </div>
      <div class="overlap-group1-2">
        <button type="submit" class="button-search" hx-post="{% url 'main:search-worker' %}" hx-target="#searched_workers">Pretraži</button>
      </div>
  </form>
{% endblock %}

ERV/main/templates/partials/graph_button.html
{% load static %}
{% now "Y" as current_year %}
<button
  hx-get="{% url 'main:bar_graph' pk=record.id year=current_year month='Ukupno' %}"
  hx-target="#graph"
  hx-trigger="click"
  hx-swap="innerHTML"
  class="border-0 bg-transparent"
>
    <i class="bi bi-bar-chart-line"></i>
</button>

ERV/main/templates/partials/jobs_form.html
{% load crispy_forms_tags %}
{% for field in filter.form %}
{% if field.label == 'Posao' %}
    <div id="jobs">
    {{ field|as_crispy_field }}
    </div>
{% endif %}
{% endfor %}

ERV/main/templates/partials/result_searched_workers_tables.html
{{post}}
<table>
  <tr class="tr">
    <th class="th">Ime</th>
    <th class="th">Prezime</th>
    <th class="th">Vrijeme ulaza</th>
    <th class="th">Vrijeme izlaza</th>
    <th class="th">Datum</th>
    <th class="th">Šifra</th>
    <th class="th">Delta vrijeme</th>
  </tr>

  {% if results %} {{results}} {% for w in results %}
  <tr class="tr">
    <td class="td">{{w.worker.name}}</td>
    <td class="td">{{w.worker.surname}}</td>
    <td class="td">{{w.enter_time|date:"H:i:s"}}</td>
    <td class="td">{{w.exit_time|date:"H:i:s"}}</td>
    <td class="td">{{w.current_date|date:"d/m/y"}}</td>
    <td class="td">{{w.flag}}</td>
    <td class="td"></td>
  </tr>
  {% endfor %} {% endif %}
</table>

ERV/main/templates/partials/upload_form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<form
  hx-encoding="multipart/form-data"
  hx-post="{% url 'main:upload_csv' %}"
  class="modal-content"
>
  {% csrf_token %}
  <div class="modal-header">
    <h3 class="modal-title">Učitaj CSV</h3>
  </div>

  <div class="modal-body">
    <input type="file" name="csv" />

    <span>Dozvoljeni formati: CSV</span>
  </div>
  <div class="modal-footer">
    <button
      style="
        border-radius: 6px;
        background-color: #6cb5b5;
        border: none;
        padding: 5px 10px;
        text-align: center;
        margin: 4px 2px;
        opacity: 0.5;
        transition: 0.3s;
        display: inline-block;
        cursor: pointer;
        color: black;
        font-weight: bold;
      "
      type="button"
      data-bs-dismiss="modal"
    >
      Odustani
    </button>
    <button
      style="
        background-color: #8cd8a6;
        border-radius: 6px;
        border: none;
        padding: 5px 10px;
        text-align: center;
        margin: 4px 2px;
        opacity: 1;
        transition: 0.3s;
        display: inline-block;
        cursor: pointer;
        color: black;
        font-weight: bold;
      "
      type="submit"
      hx-indicator=".progress"
    >
      Spremi
    </button>
    <div class="progress">
      <div class="indeterminate"></div>
    </div>    
  </div>
</form>

ERV/main/templates/partials/worker_form.html
{% load widget_tweaks %} {% with WIDGET_ERROR_CLASS='is-invalid' %}
<form
  hx-post="{{ request.path }}"
  hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
  class="modal-content"
>
  <div class="modal-header">
    <h3 class="modal-title">Dodja Radnika</h3>
  </div>

  <div class="modal-body">
    <div class="mb-3">
      <label for="{{ form.name.id_for_label }}" class="form-label">Ime</label>
      {% render_field form.name class="form-control" %}
      <div class="invalid-feedback input-medium">
        {{ form.name.errors|first }}
      </div>
    </div>

    <div class="mb-3">
      <label for="{{ form.surname.id_for_label }}" class="form-label"
        >Prezime</label
      >
      {% render_field form.surname class="form-control" %}
      <div class="invalid-feedback input-small">
        {{ form.surname.errors|first }}
      </div>
    </div>

    <div class="mb-3">
      <label for="{{ form.job.id_for_label }}" class="form-label">Posao</label>
      {% render_field form.job class="form-control" %}
      <div class="invalid-feedback">{{ form.job.errors|first }}</div>
    </div>

    <div class="mb-3">
      <label for="{{ form.active.id_for_label }}" class="form-label"
        >Aktivan</label
      >
      {% render_field form.active class="form-check-input" type="checkbox" %}
      <div class="invalid-feedback">{{ form.active.errors|first }}</div>
    </div>
  </div>

  <div class="modal-footer">
    <button
      style="
        border-radius: 6px;
        background-color: #6cb5b5;
        border: none;
        padding: 5px 10px;
        text-align: center;
        margin: 4px 2px;
        opacity: 0.5;
        transition: 0.3s;
        display: inline-block;
        cursor: pointer;
        color: black;
        font-weight: bold;
      "
      type="button"
      class="btn btn-secondary"
      hx-get="{% url 'main:add_erv' %}"
    >
      Odustani
    </button>
    <button
      style="
        background-color: #8cd8a6;
        border-radius: 6px;
        border: none;
        padding: 5px 10px;
        text-align: center;
        margin: 4px 2px;
        opacity: 1;
        transition: 0.3s;
        display: inline-block;
        cursor: pointer;
        color: black;
        font-weight: bold;
      "
      type="submit"
      class="btn btn-primary"
    >
      Spremi
    </button>
  </div>
</form>
{% endwith %}